version: '3.7'
services:
  go-library-service-db:
    container_name: go-library-service-db
    image: postgres:10.6
    ports:
      - "19002:5432"
    environment:
      - POSTGRES_PASSWORD:postgres
      - POSTGRES_USER:postgres